spring:
  application:
    name: moviesite

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_site
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  resources:
    cache:
      period: 0

  servlet:
    multipart:
      enabled: true  # Enable multipart uploads
      max-file-size: 50MB  # Optional: Set file size limit
      max-request-size: 50MB  # Optional: Set request size limit

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000  # a day
      refresh-token:
        expiration: 604800000  # 7 days

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

